#PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
max_distance: 1
n_tests: 10000

# HUMAN-AWARE COST FUNCTION CONFIGURATION
base_frame: "world"
tool_frame: "end_effector"
max_step_size: 0.01
object_type: "red_box"
n_object: 10
n_threads: 4
