# PLANNING CONFIGURATIONS:
group_name: "cartesian_arm"
utopia_tolerance: 0.05
extend: false
max_distance: 0.5
rewire_radius: 0.51
start_configuration: [0.0,0.0,0.0]
stop_configuration:  [3.0,3.0,3.0]
solver_time: 60.0

# HUMAN-AWARE COST FUNCTION CONFIGURATION
base_frame: "world"
tool_frame: "end_effector"
object_type: "sphere"
n_object: 20
poi_names: ["end_effector"]
use_vh: true

max_step_size: 0.005
max_cart_acc: 2.5
Tr: 0.15
min_distance: 0.2
v_h: 1.6

parallel_ssm: false
n_threads: 4

display_tree: true
